using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Mystia.SourceGenerators;

[Generator]
public sealed class ModEntranceGenerator : IIncrementalGenerator
{
    public const string DiagnosticId = "MYSTIA001";

    private static readonly DiagnosticDescriptor MissingConstructor = new(
        DiagnosticId,
        "AutoWire type needs a public parameterless constructor",
        "Type '{0}' implements an [AutoWire] interface but has no public parameterless constructor",
        "Mystia",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (production, compilation) =>
        {
            var model = EntranceWriter.Create(compilation, MissingConstructor);
            foreach (var diagnostic in model.Diagnostics)
                production.ReportDiagnostic(diagnostic);
            if (model.Source is not null)
                production.AddSource("ModEntrance.g.cs", SourceText.From(model.Source, Encoding.UTF8));
        });
    }
}

internal static class EntranceWriter
{
    public static EntranceModel Create(Compilation compilation, DiagnosticDescriptor missingConstructor)
    {
        var autoWire = compilation.GetTypeByMetadataName("Mystia.AutoWireAttribute");
        if (autoWire is null)
            return new EntranceModel(null, []);

        var diagnostics = new List<Diagnostic>();
        var registrations = new List<Registration>();
        foreach (var type in EnumerateTypes(compilation.Assembly.GlobalNamespace))
        {
            if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsStatic || type.IsGenericType)
                continue;
            if (type.Name.Contains('<'))
                continue;
            if (type.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                continue;

            var interfaces = type.AllInterfaces
                .Where(iface => HasAutoWire(iface, autoWire))
                .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .OrderBy(iface => iface.ToDisplayString(), StringComparer.Ordinal)
                .ToArray();
            if (interfaces.Length == 0)
                continue;

            if (!HasPublicParameterlessConstructor(type))
            {
                var location = type.Locations.FirstOrDefault(static location => location.IsInSource)
                    ?? Location.None;
                diagnostics.Add(Diagnostic.Create(missingConstructor, location, type.ToDisplayString()));
                continue;
            }

            registrations.Add(new Registration(type, interfaces));
        }

        registrations.Sort(static (left, right) => string.CompareOrdinal(
            left.Type.ToDisplayString(),
            right.Type.ToDisplayString()));

        return new EntranceModel(Render(registrations), diagnostics);
    }

    private static string Render(IReadOnlyList<Registration> registrations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("[assembly: global::Mystia.ModEntranceAttribute(typeof(global::Mystia.Generated.ModEntrance))]");
        builder.AppendLine();
        builder.AppendLine("namespace Mystia.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    public static class ModEntrance");
        builder.AppendLine("    {");
        builder.AppendLine("        public static void Register(global::Mystia.IModRegistrar registrar)");
        builder.AppendLine("        {");
        for (var index = 0; index < registrations.Count; index++)
        {
            var registration = registrations[index];
            var variable = "instance" + index.ToString(System.Globalization.CultureInfo.InvariantCulture);
            var typeName = registration.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.Append("            var ").Append(variable).Append(" = new ").Append(typeName).AppendLine("();");
            foreach (var iface in registration.Interfaces)
            {
                var interfaceName = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var key = FindStringKey(iface);
                if (key is null)
                {
                    builder.Append("            registrar.Add<").Append(interfaceName).Append(">(").Append(variable).AppendLine(");");
                }
                else
                {
                    builder.Append("            registrar.Add<").Append(interfaceName).Append(">(")
                        .Append(variable).Append('.').Append(key).Append(", ").Append(variable).AppendLine(");");
                }
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string? FindStringKey(INamedTypeSymbol iface)
    {
        foreach (var member in iface.GetMembers("Key"))
        {
            if (member is IPropertySymbol property
                && property.Type.SpecialType == SpecialType.System_String
                && property.GetMethod is not null)
            {
                return property.Name;
            }
        }

        return null;
    }

    private static bool HasAutoWire(INamedTypeSymbol iface, INamedTypeSymbol autoWire)
    {
        foreach (var attribute in iface.GetAttributes())
        {
            if (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, autoWire))
                return true;
        }

        return false;
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol type)
    {
        foreach (var constructor in type.InstanceConstructors)
        {
            if (constructor.Parameters.Length == 0 && constructor.DeclaredAccessibility == Accessibility.Public)
                return true;
        }

        return false;
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol root)
    {
        var stack = new Stack<INamespaceOrTypeSymbol>();
        stack.Push(root);
        while (stack.Count > 0)
        {
            var current = stack.Pop();
            switch (current)
            {
                case INamespaceSymbol ns:
                    foreach (var member in ns.GetMembers())
                    {
                        if (member is INamespaceOrTypeSymbol child)
                            stack.Push(child);
                    }
                    break;
                case INamedTypeSymbol type:
                    yield return type;
                    foreach (var nested in type.GetTypeMembers())
                        stack.Push(nested);
                    break;
            }
        }
    }

    private sealed class Registration(INamedTypeSymbol type, IReadOnlyList<INamedTypeSymbol> interfaces)
    {
        public INamedTypeSymbol Type { get; } = type;

        public IReadOnlyList<INamedTypeSymbol> Interfaces { get; } = interfaces;
    }
}

internal sealed class EntranceModel(string? source, IReadOnlyList<Diagnostic> diagnostics)
{
    public string? Source { get; } = source;

    public IReadOnlyList<Diagnostic> Diagnostics { get; } = diagnostics;
}
